export enum DiagnosticCode {
  GenericUnsupportedSyntax = 110000,
  UnknownType,
  UnknownSymbol,
  InvalidBuiltinReference,
  InvalidBuiltinModify,
  InvalidBuiltinUsage,
  InvalidContractEvent,
  InvalidContractProperties,
  InvalidContractMethod,
  UnknownCall,
  InvalidSmartContractType,
  InvalidNotifierType,
  InvalidLiteral,
  Invariant,
  MultipleSignatures,
  UnknownModule,
  ReferenceError,
  InvalidLinkedSmartContract,
  InvalidCurrentTime,
  InvalidSenderAddress,
  InvalidStructuredStorageFor,
}
