export enum DiagnosticCode {
  GenericUnsupportedSyntax = 0,
  UnknownType,
  UnknownSymbol,
  InvalidBuiltinReference,
  InvalidBuiltinIndex,
  InvalidBuiltinInstanceof,
  InvalidBuiltinImplement,
  InvalidBuiltinModify,
  InvalidContractEvent,
  InvalidContractProperties,
  InvalidContractMethod,
  InvalidSyscall,
  ReferenceError,
}
