#!/bin/bash
set -e
# pwd
package=$(cat package.json | node ../../../common/temp/node_modules/.bin/json name)
version=$(cat package.json | node ../../../common/temp/node_modules/.bin/json version)
published=$(npm info $package@$version version || echo "0")
if [[ "$version" = "$published" ]]; then
  echo "⚠️   $package@$version is already published!"
else
  echo "📦  Publishing: $package@$version (published: $published)"
  # Switch to yarn publish --non-interactive once it's released
  yarn publish --non-interactive $@
fi
