#!/bin/bash
set -e
# pwd
package=$(cat package.json | node ../../node_modules/.bin/json name)
version=$(cat package.json | node ../../node_modules/.bin/json version)
published=$(yarn info $package@$version version)
if [[ "$version" = "$published" ]]; then
  echo "⚠️   $package@$version is already published!"
else
  echo "📦  Publishing: $package@$version (published: $published)"
  # Switch to yarn publish --non-interactive once it's released
  npm publish $@
fi
