name: cypress10
on: [push, pull_request]
jobs:
  cypress10:
    name: cypress10
    runs-on: ubuntu-18.04
    container:
      image: spencercorwin/neo-one-gh-actions-test:latest
    steps:
      - run: pwd && ls
      - run: git clone https://github.com/neo-one-suite/neo-one.git neo-one-run && cd neo-one-run
      - run: cd neo-one-run && yarn install
      - run: cd neo-one-run && mkdir .nyc_output
      - run: cd neo-one-run && yarn website:start:prod-builds
      - run: cd neo-one-run && yarn website:start:prod
      - run: cd neo-one-run && yarn nyc report --reporter=json
      - run: cd neo-one-run && yarn run codecov -f coverage/coverage-final.json -F cypress
