name: Push DockerHub Node
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  node:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
      - uses: ./actions/dockerhub/
        with:
          args: -f ./scripts/DockerfileNode .
        env:
          DOCKER_NAMESPACE: neoonesuite
          DOCKER_IMAGE_NAME: node
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  node-gsutil:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
      - uses: ./actions/dockerhub/
        with:
          args: -f ./scripts/DockerfileNodeGSUtil .
        env:
          DOCKER_NAMESPACE: neoonesuite
          DOCKER_IMAGE_NAME: node-gsutil
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
