name: Cypress
on:
  push:
    branches:
      - master-2.x
      - staging
      - trying
  pull_request:
    branches:
      - master-2.x
      - staging
      - trying
jobs:
  cypress12:
    name: cypress12
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Node
        run: brew update-reset && brew update && brew install node@10 && brew link node@10 --force
      - name: Install Chrome
        run: brew install --cask google-chrome
      - name: Install Rush
        run: npm i -g @microsoft/rush@latest
      - name: Rush Install
        run: rush install
      - name: Rush Rebuild
        run: rush rebuild
      - name: Prune node_modules
        run: rush prune-node-modules
      - name: Rush Link Root
        run: rush link-root
      - name: Run Cypress Express Test
        run: rush test-cypress --express
      - name: Store Cypress Screenshots
        if: failure()
        continue-on-error: true
        uses: actions/upload-artifact@184d73b71b93c222403b2e7f1ffebe4508014249
        with:
          name: cypress-screenshots
          path: cypress/screenshots
