name: Cypress
on:
  push:
    branches:
      - master
      - staging
      - trying
      - master-2.x
  pull_request:
    branches:
      - master
      - staging
      - trying
      - master-2.x
jobs:
  cypress12:
    name: cypress12
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@94d077c24971944d312dd9197c1bdfba62b39878
      - name: Install Node
        run: brew update-reset && brew update && brew install node@10 && brew link node@10 --force
      - name: Install Chrome
        run: brew install --cask google-chrome
      - name: Install Rush
        run: npm i -g @microsoft/rush@latest
      - name: Rush Install
        run: rush install
      - name: Rush Rebuild
        run: rush rebuild
      - name: Prune node_modules
        run: rush prune-node-modules
      - name: Rush Link Root
        run: rush link-root
      - name: Run Cypress Express Test
        run: rush test-cypress --express
      - name: Store Cypress Screenshots
        if: failure()
        continue-on-error: true
        uses: actions/upload-artifact@e20a7983ecacb840d6004bbaa6dd6f75eaff8af7
        with:
          name: cypress-screenshots
          path: cypress/screenshots
